local namespace = _G.AVM_PITWALL_F1

namespace.config = {
  product_name = "AVM PitWall",
  build_name = "F1 DEV",
  default_mode = "compact",
  modes = { "compact", "expanded", "garage" },
  default_scenario = "NORMAL_ON_PLAN_DRY",
  max_alert_repeats = 3,
  alert_repeat_seconds = { critical = 8, high = 14, normal = 24, low = 40 },
  alert_expiry_seconds = { critical = 120, high = 90, normal = 55, low = 35 },
  max_text_length = 96,
  max_scenario_history = 4,
  sound_volume = 0.7,
  ui_scale = 1.0,
  default_source_mode = "live",
  derived_update_period_s = 0.12,
  weather_update_period_s = 1.0,
  telemetry_stale_after_s = 2.0,
  source_transition_confirmations = 2,
  max_source_transitions = 16,
  max_samples = 12,
  max_weather_samples = 20,
  max_recent_snapshots = 48,
  max_events = 128,
  max_discontinuities = 24,
  calibration_speed_limit_kmh = 10,
  calibration_arm_timeout_s = 8,
  refuel_jump_l = 1.0,
  track_overrides = {},
  targets = {
    stint_minutes = nil,
    planned_pit_lap = nil,
    pace_s = nil,
    fuel_per_lap_l = nil,
    fuel_at_pit_l = nil,
    fuel_delta_threshold_l = 1.0,
    fuel_comparison_threshold_l = 0.05,
    pace_delta_threshold_s = 0.50,
    pressure_delta_threshold_psi = 0.50,
    temperature_delta_threshold_c = 15,
    pressure_unit = "psi",
    pressure_targets_psi = {},
    temperature_targets_c = {},
    endurance_rules = {},
    strategy_profile = nil,
  },
}
